Tilemap = [
    'BBBBBBBBBBBBBBBBBBBBBB',
    'B....................B',
    'B.................E.KB',
    'B.....ELL.....LLBBBIKB',
    'B....KKKK...........KB',
    'B....II.....E........B',
    'B........LLLBKB......B',
    'B...........KKB......B',
    'B..BBB..........BBB..B',
    'B..BKK..........KKB..B',
    'B..BKI...LBBL...IKB..B',
    'B..BKI...LBBL...IKB..B',
    'B..BKK..........KKB..B',
    'B..BBB.......B..BBB..B',
    'B........LL..B.......B',
    'B....BBBK............B',
    'B.......KBBI..IBB....B',
    'B.....KKK.......B....B',
    'B.....BBB......BB....B',
    'B.........P..........B',
    'B....................B',
    'BBBBBBBBBBBBBBBBBBBBBB',
] #сітка мапи